<div class="seotoaster container" id="webbuilder-featured-only">
    <?php echo $this->partial(
        'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array(
            'innerHeaderHtml' => $this->translate('Feature pages by tags')
        )
    ); ?>
    <form id="farea-form" class="pluginform grid_12 content-auto" name="fareaForm" action="" method="post">
        <fieldset class="wrap" style="height: 210px;">
            <select id="selectFarea" class="grid_12" name="selectFarea">
                <option value=""><?php echo $this->translate('Select page tag');?></option>
                    <?php if(isset($this->areas) && !empty($this->areas)):?>
                        <?php foreach($this->areas as $farea): ?>
                            <?php
                            $name = $farea->getName();
                            $selected = !empty($this->content) && ($farea->getName() == $this->content[0]) ? 'selected="selected"' : '';
                            ?>
                            <option value="<?php echo $farea->getName();?>" <?php echo $selected; ?> ><?php echo $farea->getName(); ?></option>
                        <?php endforeach; ?>
                    <?php endif;?>
            </select>

            <div class="grid_12">
                <label class="grid_5 alpha mt5px"><?php echo $this->translate('Max results');?></label>
                <input class="grid_7 alpha omega" type="text" id="maxRes" name="max_res" value="<?php echo isset($this->content[1]) ? $this->content[1] : Widgets_Featuredonly_Featuredonly::FA_DEFAULT_MAX_PAGES_COUNT;?>"/>
            </div>
            <?php $showCrop = ($this->useImage == 'imgc') ?>
            <div class="grid_12 maxchars">
                <label class="grid_5 alpha mt5px"><?php echo $this->translate('Max characters');?></label>
                <input id="maxChar" class="grid_7 alpha omega" type="text" name="max_char" maxlength="3" value="<?php echo (isset($this->content[2]) && $this->content[2] != '') ? $this->content[2] : Widgets_Featuredonly_Featuredonly::FA_DEFAULT_DESCRIPTION_LIMIT;?>" /><br />
            </div>
            <div class="grid_12">
                <label class="grid_6 alpha omega">
                    <span class="grid_10 alpha omega"><?php echo $this->translate('Use image'); ?></span>
                    <input id="useImg" type="checkbox" name="useImage" <?php echo (isset($this->useImage) && ($this->useImage == 'img' || $this->useImage == 'imgc')) ? 'checked="checked"' : ''; ?> />
                </label>
                <label class="cropped-img grid_6 omega <?php echo ($this->useImage == 'img' || $this->useImage == 'imgc') ? '' : 'hide'; ?>">
                    <?php echo $this->translate('Cropped'); ?>
                    <input id="cropImg" type="checkbox" name="crop_img" <?php echo ($showCrop == 'imgc') ? 'checked="checked"' : ''; ?> />
                </label>
            </div>
            <div class="grid_12 crop-size <?php echo ($showCrop == 'imgc') ? '' : 'hide'; ?>">
                <p class="clearfix">
                    <label class="mt5px grid_5 alpha"><?php echo $this->translate('Size'); ?></label>
                    <?php echo $this->formText('width', $this->width, array('class' => 'width grid_3 omega alpha', 'placeholder' => $this->translate('Width'))); ?>
                    <span class="mt5px grid_1 alpha omega text-center">X</span>
                    <?php echo $this->formText('height', $this->height, array('class' => 'height grid_3 omega alpha', 'placeholder' => $this->translate('Height'))); ?>
                </p>
            </div>
            <div class="grid_12">
                <label class="grid_5 alpha"><?php echo $this->translate('Random');?>?</label>
                <?php $random = (isset($this->content[4]) && $this->content[4] == '1') || (isset($this->content[3]) && $this->content[3] == '1') ?>
                <input id="rand" type="checkbox" name="rand" <?php echo ($random) ? 'checked="checked"' : ''; ?> />
            </div>
        </fieldset>
        <input type="hidden" id="container" name="container" value="<?php echo $this->containerName?>" />
        <input type="hidden" id="pageId" name="pageId" value="<?php echo $this->pageId?>" />
        <div class="footer grid_12">
            <a class="error ml-grid" id="delete-fa" href="javascript:;">[ Delete ]</a>
            <button id="submit" class="btn ticon-save mr-grid" type="submit"><?php echo $this->translate('Done');?></button>
        </div>
    </form>
</div>

<script type="text/javascript" >
    $(function() {
        $(document).on('submit', '#farea-form', function() {
            var fareaName = $("#selectFarea option:selected").val();

            if(fareaName == ''){
                showMessage('<?php echo $this->translate('Please select Featuredarea');?>', true);
                return false;
            }

            $.ajax({
                type     : 'post',
                url      : '<?php echo $this->websiteUrl; ?>api/webbuilder/fo/',
                dataType : 'json',
                data     : {
                    pageId        : $('#pageId').val(),
                    maxRes        : $('#maxRes').val(),
                    maxChar       : $('#maxChar').val(),
                    containerName : $('#container').val(),
                    useImg        : $('#useImg').is(':checked') ? 1 : 0,
                    cropImg       : $('#cropImg').is(':checked') ? 1 : 0,
                    width         : $('#width').val(),
                    height        : $('#height').val(),
                    rand          : $('#rand').is(':checked') ? 1 : 0,
                    areaName      : fareaName,
                    secureToken   : '<?php echo Tools_System_Tools::initSecureToken(Webbuilder::WB_FAREA_SECURE_TOKEN);?>'
                },
                beforeSend: showSpinner()
            }).done(function() {
                top.location.reload();
            });

            return false;
        });

    });
    $(function() {
        $(document).on('click', '#delete-fa', function() {
            var fareaName = $("#selectFarea option:selected").val();
            $.ajax({
                type     : 'delete',
                url      : '<?php echo $this->websiteUrl; ?>api/webbuilder/fo/',
                dataType : 'json',
                data     : {
                    pageId        : $('#pageId').val(),
                    containerName : $('#container').val(),
                    areaName      : fareaName
                },
                beforeSend: showSpinner()
            }).done(function() {
                    top.location.reload();
                });

            return false;
        });

    });
</script>
