<div class="seotoaster container" id="webbuilder-text-only">
    <?php echo $this->partial(
        'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array(
            'innerHeaderHtml' => $this->translate('Text only')
        )
    ); ?>
    <form id="text-only" class="_fajax _reload content grid_12" action="<?php echo $this->websiteUrl;?>api/webbuilder/to/" method="post" xmlns="http://www.w3.org/1999/html">
        <textarea id="text-only-content" name="content" class="tinymce"><?php echo $this->content; ?></textarea>
        <input type="hidden" id="containerName" name="containerName" value="<?php echo $this->containerName; ?>"/>
        <input type="hidden" id="pageId" name="pageId" value="<?php echo $this->pageId;?>"/>
        <input type="hidden" name="<?php echo Tools_System_Tools::CSRF_SECURE_TOKEN;?>" value="<?php echo Tools_System_Tools::initSecureToken(Webbuilder::WB_TEXTONLY_SECURE_TOKEN);?>" />
        <div class="footer cl-both">
            <button id="submit" class="btn ticon-save" name="submit" type="submit"><?php echo $this->translate('Save content'); ?></button>
        </div>
    </form>
    <input type="hidden" id="reset_css" value="<?php echo Tools_Theme_Tools::urlResetCss(); ?>" />
    <input type="hidden" id="content_css" value="<?php echo Tools_Theme_Tools::urlContentCss(); ?>" />
</div>
<?php $this->headScript()
           ->appendFile($this->websiteUrl . 'system/js/external/tinymce/tinymce.min.js'); ?>
<script type="text/javascript">
    tinymce.init({
        script_url              : '<?php echo $this->websiteUrl; ?>system/js/external/tinymce/tinymce.gzip.php',
        selector                : "textarea.tinymce",
        skin                    : 'seotoaster',
        width                   : '100%',
        height                  : '380px',
        menubar                 : false,
        resize                  : false,
        convert_urls            : false,
        relative_urls           : false,
        statusbar               : false,
        content_css             : $('#reset_css').val()+','+$('#content_css').val(),
        importcss_file_filter   : "content.css",
        importcss_groups : [
            {title : 'Button styles', filter : /^(.btn*|button\.)/},
            {title : 'Table styles', filter : /^(.table*|table\.|tr\.|td\.|th\.)/},
            {title : 'List styles', filter : /^(.list*|ul\.|ol\.)/},
            {title : 'Image styles', filter : /^(.image*|img\.)/},
            {title : 'Block quote styles', filter : /^(blockquote\.)/},
            {title : 'Separator styles', filter : /^(hr\.)/},
            {title : 'Primary colors', filter : /^(\.primary*|\.green|\.blue|\.orange|\.red|\.color*)/},
            {title : 'Size classes', filter : /^(\.larger|\.large|\.small|\.mini|\.size*)/},
            {title : 'Other styles'}
        ],
        plugins                 : [
            "advlist lists link charmap code paste importcss textcolor stw"
        ],
        importcss_merge_classes : true,
        toolbar1                : "bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist | forecolor backcolor | link unlink | pastetext removeformat",
        toolbar2                : "stw | styleselect | formatselect | fontsizeselect | hr charmap | code",
        fontsize_formats        : "8px 10px 12px 14px 16px 18px 24px 36px",
        block_formats           : "Block=div;Paragraph=p;Block Quote=blockquote;Address=address;Code=code;Preformatted=pre;H2=h2;H3=h3;H4=h4;H5=h5;H6=h6",
        link_list               : '<?php echo $this->websiteUrl; ?>backend/backend_page/linkslist/',
        image_advtab            : true,
        setup                   : function(ed){
            ed.on("blur", function(){
                this.save();
            });
        }
    });
</script>

