<?php
    $this->headLink()
        ->appendStylesheet($this->websiteUrl."plugins/netcontent/web/css/netcontent.css" );
    $this->headScript()
        ->appendFile($this->websiteUrl."plugins/netcontent/web/js/netcontent.min.js" );
?>

<?php if($this->isP2p) : ?>
<label>p2p</label> <input type="checkbox" data-url="<?php echo $this->websiteUrl;?>plugin/netcontent/run/saveNetContent" id="p2p-content" name="p2p" />&nbsp;
<?php endif;?>