<?php if(isset($this->image)): ?>
    <?php
        $image    = '<img alt="' . (isset($this->description) ? $this->description : $this->image) . '" width="' . $this->width . '" src="' .$this->websiteUrl . 'media/' . $this->folder . '/' . $this->mediaSubFolder . '/' . $this->image . '" />';
        $imageUrl = ($this->linkedTo == Widgets_Imageonly_Imageonly::LINK_OPTION_URL) ? $this->externalUrl : $this->websiteUrl . 'media/' . $this->folder . '/original/' . $this->image;
    ?>
    <?php if($this->linkedTo == Widgets_Imageonly_Imageonly::LINK_OPTION_NOTHING): ?>
        <?php echo $image; ?>
    <?php else: ?>
        <a <?php if ($this->linkedTo == Widgets_Imageonly_Imageonly::LINK_OPTION_URL) : ?>
            <?php echo $this->target === '_self' ? '' : 'target="_blank"' ?>
        <?php else: ?>
            <?php echo 'class="_lbox"'; ?>
        <?php endif ?>
            title="<?php echo $this->description; ?>" href="<?php echo $imageUrl; ?>">
        <?php echo $image; ?>
        </a>
    <?php endif; ?>
<?php endif; ?>
<?php  if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_CONTENT) && !$this->readonly):?>
    <a href="javascript:;" class="tpopup" data-pwidth="480" data-pheight="560" data-url="<?php echo $this->websiteUrl;?>plugin/webbuilder/run/imageonly/containerName/<?php echo $this->containerName; ?>/pid/<?php echo $this->pageId;?>">
        <img alt="<?php echo $this->translate('Image only'); ?>" src="<?php echo $this->websiteUrl;?>plugins/webbuilder/web/images/imageonly.png" />
    </a>
<?php endif;?>