<?php
$this->headScript()->appendFile("http://www.google.com/jsapi" );
echo $this->headScript();
?>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart, table"]});
    google.setOnLoadCallback(drawColumnCoupon);
    function drawColumnCoupon(type) {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Coupons');
        data.addColumn('number', 'Count');
        data.addRows([
            <?php foreach($this->data as $key => $value):?>
            ["<?php echo $key;?>",<?php echo $value;?>],
            <?php endforeach;?>
        ]);
        var options = {
            title: 'Sales count by Coupon',
            hAxis: {title: 'Period'},
            legend:{position:'right'},
            height:'<?php echo $this->height;?>',
            titleTextStyle: {fontSize:"14"}

        };

        var columnchart = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnCouponTable'));
        columnchart.draw(data, options);

        if(type === 'table') {
            var table = new google.visualization.Table(document.getElementById('visualizationcolumnCouponTable'));
            table.draw(data, {page: 'enable', pageSize: 15, showRowNumber: true, width: '100%', height: '<?php echo $this->height;?>px'}, options);
        }
        if(type === 'columnchart')  {
            var columnchart = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnCouponTable'));
            columnchart.draw(data, options);
        }
    }

</script>
<div id="visualizationcolumnCouponTable" style="width:100%;height:<?php echo $this->height;?>px;"></div>
<input type="hidden" class="typeOfGraficCoupon" value="<?php echo $this->typeSalesAmount;?>" />

<div id="viewCoupon" class="btn success fl-left mt5px">Change view</div>
<script>
    $('#viewCoupon').on('click', function() {
        if ($.cookie('c') == 'table') {
            $.cookie('c', 'columnchart');
        } else {
            $.cookie('c', 'table');
        }
        drawColumnCoupon($.cookie('c'));
    });
</script>
<div class="exportCoupon">
    <a class="btn ticon-box-add success fl-left mt5px ml-grid" id="exportCoupon" title="" href="<?php echo $this->websiteUrl?>plugin/toasterstats/run/period/paramsCoupon/<?php echo $this->period;?>">
        <?php echo $this->translate('Export CSV'); ?>
    </a>
</div>
