<?php
$this->headScript()->appendFile("http://www.google.com/jsapi" );
echo $this->headScript();
?>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart, table"]});
    google.setOnLoadCallback(drawColumnTag);
    if($.removeCookie('t') !== false) {
        $.removeCookie('t');
    }

    function drawColumnTag(type) {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Tags');
        data.addColumn('number', 'Count');
        data.addRows([
            <?php foreach($this->data as $key => $value):?>
            ["<?php echo $key;?>",<?php echo $value;?>],
            <?php endforeach;?>
        ]);
        var options = {
            legend:{position:'right'},
            height:'100%',
            titleTextStyle: {fontSize:"14"}
        };
        var columnchart = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnTagTable'));
        columnchart.draw(data, options);

        if(type === 'table') {
            var table = new google.visualization.Table(document.getElementById('visualizationcolumnTagTable'));
            table.draw(data, {page: 'enable', pageSize: 15, showRowNumber: true, width: '100%', height: '25px;'}, options);
        }
        if(type === 'columnchart') {
            var columnchart = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnTagTable'));
            columnchart.draw(data, options);
        }
    }

</script>
<div id="visualizationcolumnTagTable" style="width:100%;height:<?php echo $this->height;?>px;"></div>
<input type="hidden" class="typeOfGraficTag" value="<?php echo $this->typeSales;?>" />

<div id="viewTag" class="btn success fl-left mt5px">Change view</div>
<script>
    $('#viewTag').on('click', function() {
        if ($.cookie('t') == 'table') {
            $.cookie('t', 'columnchart');
        } else {
            $.cookie('t', 'table');
        }
        drawColumnTag($.cookie('t'));
    });
</script>
<div class="exportTag">
    <a class="btn ticon-box-add success fl-left mt5px ml-grid" id="exportTag" title="" href="<?php echo $this->websiteUrl?>plugin/toasterstats/run/period/paramsTag/<?php echo $this->period;?>/">
        <?php echo $this->translate('Export CSV'); ?>
    </a>
</div>
