<?php
$this->headScript()->appendFile("http://www.google.com/jsapi" );
echo $this->headScript();
?>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart, table"]});
    google.setOnLoadCallback(drawCoreType);
    function drawCoreType(type) {
        var data = new google.visualization.DataTable();
        data.addColumn('string', '<?php echo $this->typeSales;?>');
        data.addColumn('number', 'amount');
        data.addRows([
            <?php foreach($this->dataArray as $name => $value):?>

            ["<?php echo addslashes($name);?>", <?php echo $value;?>],
            <?php endforeach;?>
        ]);
        <?php if($this->typeSales === Toasterstats::TYPE_EMAIL_REMARKETING):?>
        var formatter = new google.visualization.NumberFormat(
            {negativeColor: 'red', negativeParens: true});
        <?php else:?>
        var formatter = new google.visualization.NumberFormat(
            {prefix: '<?php echo $this->currencySymbol;?>', negativeColor: 'red', negativeParens: true});
        formatter.format(data, 0);
        formatter.format(data, 1);
        <?php endif;?>
        <?php if($this->typeSales == 'type'):?>
        var options = {
            legend:{position:'none'},
            height:'<?php echo $this->height;?>',
            titleTextStyle: {fontSize:"14"},
            chartArea:{width:"85%",height:"85%"}
        };
        <?php endif;?>
        <?php if($this->typeSales == Toasterstats::TYPE_COUPON_SALES || $this->typeSales === Toasterstats::TYPE_EMAIL_REMARKETING):?>
        var options = {
            legend:{position:'right'},
            height:'<?php echo $this->height;?>',
            titleTextStyle: {fontSize:"14"},
            chartArea:{width:"85%",height:"85%"}
        };
        <?php endif;?>

        var chartType = new google.visualization.PieChart(document.getElementById('visualizationcolumnTypeTable'));
        chartType.draw(data, options);

        if(type === 'tableCore') {
            var tableType = new google.visualization.Table(document.getElementById('visualizationcolumnTypeTable'));
            tableType.draw(data, {page: 'enable', pageSize: 15, showRowNumber: true, width: '100%', height: '<?php echo $this->height;?>px'}, options);
        }
        if(type === 'chart')  {
            var chartType = new google.visualization.PieChart(document.getElementById('visualizationcolumnTypeTable'));
            chartType.draw(data, options);
        }
    }
</script>
<?php if($this->typeOfGrafic == 'amount'):?>
    <div id="visualizationcolumnTypeTable" style="height:<?php echo $this->height;?>px;"></div>
    <input type="hidden" class="typeOfGraficAmountType<?php echo $this->typeSales;?>" value="<?php echo $this->typeSalesAmount;?>" />
<?php endif;?>

<div id="viewcorecharttype" class="btn success fl-left mt5px">Change view</div>
<script>
    $('#viewcorecharttype').on('click', function() {
        if ($.cookie('t') == 'tableCore') {
            $.cookie('t', 'chart');
        } else {
            $.cookie('t', 'tableCore');
        }
        drawCoreType($.cookie('t'));
    });
</script>
<div class="exportType">
    <a class="btn ticon-box-add success fl-left mt5px ml-grid" id="exportType" title="" href="<?php echo $this->websiteUrl?>plugin/toasterstats/run/period/paramscorechart/<?php echo $this->period;?>/typesales/<?php echo $this->typeSales;?>/">
        <?php echo $this->translate('Export CSV'); ?>
    </a>
</div>
