<div id="products-table-period">
	<?php foreach($this->productsData as $product):?>
		<?php if($product['name'] == 'Nothing found'):?>
		<p class="text-center fs16 red"><i class="icon-neutral"></i> <?php echo $this->translate($product['name']);?></p>
		<?php endif;?>
		<?php if($product['name'] != 'Nothing found'):?>
		<p class="m0px"><a target="_blank" href="<?php echo $this->websiteUrl;?><?php echo $product['url'];?>"><i class="icon-cube-2"></i> <?php echo $product['name'];?></a></p>
		<?php endif;?>
	<?php endforeach;?>
</div>

