<script type="text/javascript">
$(document).ready(function(){
    $(function(){
        $("#datepickerFrom").datepicker();
        $("#datepickerFrom").datepicker("option", "dateFormat", 'd-M-yy');
        $("#datepickerTo").datepicker();
        $("#datepickerTo").datepicker("option", "dateFormat", 'd-M-yy');
        var defaultDateFromDatepiker = $('.defaultFromDatepiker').val();
        var defaultDateToDatepiker = $('.defaultToDatepiker').val();
        $('#datepickerFrom').val(defaultDateFromDatepiker);
        $('#datepickerTo').val(defaultDateToDatepiker);
        $('#enableShippingForGraf').prop('checked', true);
    });

    $("#redrawSales").on('click', function(){
        if($('#datepickerFrom').val()!='' && $('#datepickerTo').val()!=''){
            changeSales('changedPeriod');
        }
    });

    function changeSales(period){
        var salesPeriod = '',
            countGrafic = 0,
            amountGrafic = 0,
            defaultTimePeriod = 0,
            taxesState = 0,
            countTagGrafic = 0,
            countCouponGraf = 0,
            geoGraf = 0,
            pierchartAmountGrafics = [],
            countEmailRemarketingGraf = 0,
            restoredEmailRemarketingGraf = 0,
            shippingState = 0,
            countTagGraficTag = 0,
            countCouponGraficCoupon = 0,
            countEmailRemarketingGrafRemarketing = 0;

        if(period=='changedPeriod'){
            salesPeriod = $('#datepickerFrom').val()+'|'+$('#datepickerTo').val();
        }
        if($('#visualizationcolumnAverageAmountLinechart').length>0){
            amountGrafic = 1;
        }
        if($('#visualizationcolumnCountLinechart').length>0){
            countGrafic = 1;
        }
        if($('#visualizationcolumnCountTags').length>0){
            countTagGrafic = 1;
        }
        if($('#visualizationcolumnTagTable').length>0){
            countTagGraficTag = 1;
        }
        if($('#visualizationcolumnCountCoupons').length>0){
            countCouponGraf = 1;
        }
        if($('#visualizationcolumnCouponTable').length>0){
            countCouponGraficCoupon = 1;
        }
        if($('#visualizationGeoChart').length>0){
            geoGraf = 1;
        }
        if($('#visualizationcolumnCountRemarketings').length>0){
            countEmailRemarketingGraf = 1;
        }
        if($('#visualizationcolumnCountRemarketingTable').length>0){
            countEmailRemarketingGrafRemarketing = 1;
        }
        if($('#visualizationcolumnRemarketing').length>0){
            restoredEmailRemarketingGraf = 1;
        }
        if($('#enableTaxesGraf').is(':checked')){
            taxesState = 1;
        }
        if($('#enableShippingForGraf').is(':checked')){
            shippingState = 1;
        }
        if($('#visualizationcolumnProduct').length>0){
            pierchartAmountGrafics.push('product');
        }
        if($('#visualizationcolumnProductTable').length>0){
            pierchartAmountGrafics.push('productTable');
        }
        if($('#visualizationcolumnBrand').length>0){
            pierchartAmountGrafics.push('brand');
        }
        if($('#visualizationcolumnBrandTable').length>0){
            pierchartAmountGrafics.push('brandTable');
        }
        if($('#visualizationcolumnTag').length>0){
            pierchartAmountGrafics.push('tag');
        }
        if($('#visualizationcolumnTagTable').length>0){
            pierchartAmountGrafics.push('tagTable');
        }
        if($('#visualizationcolumnCustomer').length>0){
            pierchartAmountGrafics.push('customer');
        }
        if($('#visualizationcolumnCustomerTable').length>0){
            pierchartAmountGrafics.push('customerTable');
        }
        if($('#visualizationcolumnType').length>0){
            pierchartAmountGrafics.push('type');
        }
        if($('#visualizationcolumnTypeTable').length>0){
            pierchartAmountGrafics.push('typeTable');
        }
        if($('#visualizationcolumnCoupon').length>0){
            pierchartAmountGrafics.push('coupon');
        }
        if($('#visualizationcolumnCouponTable').length>0){
            pierchartAmountGrafics.push('couponTable');
        }
        if($('#visualizationcolumnCountRemarketingTable').length>0){
            pierchartAmountGrafics.push('remarketingTable');
        }

        $.ajax({
            type     : "POST",
            url      : '<?php echo $this->websiteUrl; ?>plugin/toasterstats/run/changeDashboardDataSales/',
            dataType : "json",
            data     : {
                timePeriod                : salesPeriod,
                averageAmountGrafic       : amountGrafic,
                countGrafic               : countGrafic,
                typeOfGraficCount         : $('.typeOfGraficCount').val(),
                typeOfGraficAverageAmount : $('.typeOfGraficAverageAmount').val(),
                taxesState                : taxesState,
                pierchartAmountGrafics    : pierchartAmountGrafics,
                countTagGrafic            : countTagGrafic,
                geoGraf                   : geoGraf,
                countCouponGraf           : countCouponGraf,
                shippingState             : shippingState,
                countEmailRemarketingGraf : countEmailRemarketingGraf,
                restoredEmailRemarketingGraf : restoredEmailRemarketingGraf,
                countTagGraficTag         : countTagGraficTag,
                countCouponGraficCoupon   : countCouponGraficCoupon,
                countEmailRemarketingGrafRemarketing : countEmailRemarketingGrafRemarketing
            },
            success  : function(responce){
                if(responce.grafData.countGraficExcist==1){
                    var data = new google.visualization.DataTable();
                    var typeOfGraficCount = responce.typeOfGraficCount;

                    if(typeOfGraficCount.match("\\u007c")){
                        data.addColumn('string', 'Date');
                        data.addColumn('number', '<?php echo $this->translate('Sales');?>');
                        data.addColumn('number', '<?php echo $this->translate('Quotes');?>');
                        $.each(responce.grafData.countGraficData, function(date, values){
                            if(date.length>7){
                                date = date.substr(5, 8);
                            }
                            data.addRows([
                                [date, values.sales, values.quotes]
                            ]);
                        });
                        var options = {
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "75%", height : "75%"}
                        };
                    }else{
                        data.addColumn('string', 'Date');
                        data.addColumn('number', typeOfGraficCount);
                        if(typeOfGraficCount=='Quotes'){
                            $.each(responce.grafData.countGraficData, function(date, values){
                                if(date.length>7){
                                    date = date.substr(5, 8);
                                }
                                data.addRows([
                                    [date, values.quotes]
                                ]);
                            });
                        }else{
                            $.each(responce.grafData.countGraficData, function(date, values){
                                if(date.length>7){
                                    date = date.substr(5, 8);
                                }
                                data.addRows([
                                    [date, values.sales]
                                ]);
                            });
                        }
                        var options = {
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "75%", height : "75%"}
                        };

                    }

                    var chart = new google.visualization.AreaChart(document.getElementById('visualizationcolumnCountLinechart'));
                    chart.draw(data, options);
                }
                if(responce.countTagExcist==1){
                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Tags');
                    data.addColumn('number', 'Count');
                    $.each(responce.countTagGraficsData, function(name, values){
                        data.addRows([
                            [name, values*1]
                        ]);
                    });
                    var options = {
                        legend         : {position : 'none'},
                        titleTextStyle : {fontSize : "14"},
                        chartArea      : {width : "85%", height : "75%"}
                    };
                    var chart = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnCountTags'));
                    chart.draw(data, options);
                }
                if(responce.countTagExcistTag == 1){
                    var dataTag = new google.visualization.DataTable();

                    dataTag.addColumn('string', 'Tags');
                    dataTag.addColumn('number', 'Count');
                        $.each(responce.countTagGraficsDataTag, function (name, values) {
                            dataTag.addRows([
                                [name, values * 1]
                            ]);
                        });
                        var options = {
                            legend:{position:'right'},
                            height:'100%',
                            titleTextStyle: {fontSize:"14"}
                        };
                        var columnchartTag = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnTagTable'));
                    columnchartTag.draw(dataTag, options);
                    if($.removeCookie('tag') !== false) {
                        $.removeCookie('tag');
                    }

                    function drawColumnTag(type) {
                        if(type === 'tableTag') {
                            var columnchartTag = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnTagTable'));
                            columnchartTag.draw(dataTag, options);
                        }
                        if(type === 'ColumnChartTag') {
                            var tableTag = new google.visualization.Table(document.getElementById('visualizationcolumnTagTable'));
                            tableTag.draw(dataTag, {
                                page: 'enable', pageSize: 15, showRowNumber: true, width: '100%', height: '25px;'
                            }, options);
                        }
                    }
                    $('#viewTag').unbind("click");
                    $('#viewTag').on('click', function() {
                        if ($.cookie('tag') == 'ColumnChartTag') {
                            $.cookie('tag', 'tableTag');
                        } else {
                            $.cookie('tag', 'ColumnChartTag');
                        }
                        drawColumnTag($.cookie('tag'));
                    });
                    var from = $('#datepickerFrom').val();
                    var to = $("#datepickerTo").val();

                    $('#exportTag').attr('href', '<?php echo $this->websiteUrl;?>plugin/toasterstats/run/period/type/tag/date/'+from+'|'+to);

            }

                if (responce.countCouponExists == 1){
                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Coupons');
                    data.addColumn('number', 'Count');
                    $.each(responce.countCouponGrafData, function(name, values){
                        data.addRows([
                            [name, values*1]
                        ]);
                    });
                    var options = {
                        legend         : {position : 'none'},
                        titleTextStyle : {fontSize : "14"},
                        chartArea      : {width : "85%", height : "75%"}
                    };
                    var chart = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnCountCoupons'));
                    chart.draw(data, options);
                }
                if (responce.countCouponExistsCoupon == 1){
                    var dataCoupon = new google.visualization.DataTable();
                    dataCoupon.addColumn('string', 'Coupons');
                    dataCoupon.addColumn('number', 'Count');
                    $.each(responce.countCouponGrafDataCoupon, function(name, values){
                        dataCoupon.addRows([
                            [name, values*1]
                        ]);
                    });
                    var options = {
                        legend         : {position : 'none'},
                        titleTextStyle : {fontSize : "14"},
                        chartArea      : {width : "85%", height : "75%"}
                    };
                    var columnchartCoupon = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnCouponTable'));
                    columnchartCoupon.draw(dataCoupon, options);

                    function drawColumnCoupon(type) {
                        if (type === 'ColumnChartCoupon') {
                            var columnchartCoupon = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnCouponTable'));
                            columnchartCoupon.draw(dataCoupon, options);
                        }
                        if (type === 'tableCoupon') {
                            var tableCoupon = new google.visualization.Table(document.getElementById('visualizationcolumnCouponTable'));
                            tableCoupon.draw(dataCoupon, {
                                page: 'enable',
                                pageSize: 15,
                                showRowNumber: true,
                                width: '100%',
                                height: '<?php echo $this->height;?>px'
                            }, options);
                        }
                    }
                    $('#viewCoupon').unbind("click");
                    $('#viewCoupon').on('click', function() {
                        if ($.cookie('coupon') == 'tableCoupon') {
                            $.cookie('coupon', 'ColumnChartCoupon');
                        } else {
                            $.cookie('coupon', 'tableCoupon');
                        }
                        drawColumnCoupon($.cookie('coupon'));
                    });

                    var from = $('#datepickerFrom').val();
                    var to = $("#datepickerTo").val();

                    $('#exportCoupon').attr('href', '<?php echo $this->websiteUrl;?>plugin/toasterstats/run/period/type/coupon/date/'+from+'|'+to);
                }

                if (responce.countEmailRemarketingExists == 1){
                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Remarketing activity');
                    data.addColumn('number', 'Count');
                    $.each(responce.countEmailRemarketingGrafData, function(name, values){
                        data.addRows([
                            [name, values*1]
                        ]);
                    });
                    var options = {
                        legend         : {position : 'none'},
                        titleTextStyle : {fontSize : "14"},
                        chartArea      : {width : "85%", height : "75%"}
                    };
                    var chart = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnCountRemarketings'));
                    chart.draw(data, options);
                }

                if (responce.countEmailRemarketingExistsRemarketing == 1){
                        var dataRemarketing = new google.visualization.DataTable();
                        dataRemarketing.addColumn('string', 'Remarketing activity');
                        dataRemarketing.addColumn('number', 'Count');
                        $.each(responce.countEmailRemarketingGrafDataRemarketing, function (name, values) {
                            dataRemarketing.addRows([
                                [name, values * 1]
                            ]);
                        });
                        var options = {
                            legend: {position: 'none'},
                            titleTextStyle: {fontSize: "14"},
                            chartArea: {width: "85%", height: "75%"}
                        };
                        var columnchartRemarketing = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnCountRemarketingTable'));
                        columnchartRemarketing.draw(dataRemarketing, options);

                    function drawColumnRemarketing(type) {
                        if (type === 'tableRemarketing') {
                            var tableRemarketing = new google.visualization.Table(document.getElementById('visualizationcolumnCountRemarketingTable'));
                            tableRemarketing.draw(dataRemarketing, {
                                page: 'enable',
                                pageSize: 15,
                                showRowNumber: true,
                                width: '100%',
                                height: '<?php echo $this->height;?>px'
                            }, options);
                        }
                        if (type === 'columnchartRemarketing') {
                            var columnchartRemarketing = new google.visualization.ColumnChart(document.getElementById('visualizationcolumnCountRemarketingTable'));
                            columnchartRemarketing.draw(dataRemarketing, options);
                        }
                    }
                    $('#viewRemarketing').unbind("click");
                    $('#viewRemarketing').on('click', function() {
                        if ($.cookie('remarketing') == 'tableRemarketing') {
                            $.cookie('remarketing', 'columnchartRemarketing');
                        } else {
                            $.cookie('remarketing', 'tableRemarketing');
                        }
                        drawColumnRemarketing($.cookie('remarketing'));
                    });
                    var from = $('#datepickerFrom').val();
                    var to = $("#datepickerTo").val();

                    $('#exportRemarketing').attr('href', '<?php echo $this->websiteUrl;?>plugin/toasterstats/run/period/type/remarketing/date/'+from+'|'+to);

                }

                if (responce.restoredEmailRemarketingGrafExists == 1){
                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Remarketing activity');
                    data.addColumn('number', 'Amount');
                    $.each(responce.restoredEmailRemarketingGrafData, function(name, values){
                        data.addRows([
                            [name, values*1]
                        ]);
                    });
                    var options = {
                        titleTextStyle : {fontSize : "14"},
                        chartArea      : {width : "85%", height : "85%"}
                    };
                    var chart = new google.visualization.PieChart(document.getElementById('visualizationcolumnRemarketing'));
                    chart.draw(data, options);
                }

                if(responce.geoGraf==1){
                    var data = new google.visualization.DataTable();
                    if(responce.geoGrafData.typeofMap=='USA'){
                        data.addColumn('string', 'States')
                    }else{
                        data.addColumn('string', 'Country')
                    }
                    data.addColumn('number', 'Customers');
                    $.each(responce.geoGrafData.mapData, function(name, values){
                        data.addRows([
                            [name, values*1]
                        ]);
                    });
                    if(responce.geoGrafData.typeofMap=='USA'){
                        var options = {
                            region     : 'US',
                            resolution : 'provinces'
                        };
                    }else{
                        var options = {

                        };
                    }
                    var chart = new google.visualization.GeoChart(document.getElementById('visualizationGeoChart'));
                    chart.draw(data, options);

                }

                if(responce.grafData.averageAmountGraficExcist==1){
                    var data = new google.visualization.DataTable();
                    var typeOfGraficAvarageAmount = responce.typeOfGraficAvarageAmount;

                    if(typeOfGraficAvarageAmount.match("\\u007c")){
                        data.addColumn('string', 'Date');
                        data.addColumn('number', '<?php echo $this->translate('Sales');?>');
                        data.addColumn('number', '<?php echo $this->translate('Quotes');?>');
                        $.each(responce.grafData.averageAmountGraficData, function(date, values){
                            if(date.length>7){
                                date = date.substr(5, 8);
                            }
                            data.addRows([
                                [date, values.sales, values.quotes]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({prefix : '<?php echo $this->currencySymbol;?>', negativeColor : 'red', negativeParens : true});
                        formatter.format(data, 0);
                        formatter.format(data, 1);
                        formatter.format(data, 2);
                        var options = {
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "75%", height : "75%"}
                        };
                    }else{
                        data.addColumn('string', 'Date');
                        data.addColumn('number', typeOfGraficAvarageAmount);
                        if(typeOfGraficCount=='Quotes'){
                            $.each(responce.grafData.averageAmountGraficData, function(date, values){
                                if(date.length>7){
                                    date = date.substr(5, 8);
                                }
                                data.addRows([
                                    [date, values.quotes]
                                ]);
                            });
                        }else{

                            $.each(responce.grafData.averageAmountGraficData, function(date, values){
                                if(date.length>7){
                                    date = date.substr(5, 8);
                                }
                                data.addRows([
                                    [date, values.sales]
                                ]);
                            });
                        }
                        var formatter = new google.visualization.NumberFormat({prefix : '<?php echo $this->currencySymbol;?>', negativeColor : 'red', negativeParens : true});
                        formatter.format(data, 0);
                        formatter.format(data, 1);
                        var options = {
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "75%", height : "75%"}
                        };
                    }
                    var chart = new google.visualization.AreaChart(document.getElementById('visualizationcolumnAverageAmountLinechart'));
                    chart.draw(data, options);
                }
                if(responce.pierchartExcist==1){
                    if(responce.pierChartData.product!==undefined){
                        var data = new google.visualization.DataTable();
                        data.addColumn('string', 'Product');
                        data.addColumn('number', 'amount');
                        $.each(responce.pierChartData.product, function(name, values){
                            data.addRows([
                                [name, values*1]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({prefix : '<?php echo $this->currencySymbol;?>', negativeColor : 'red', negativeParens : true});
                        formatter.format(data, 0);
                        formatter.format(data, 1);
                        var options = {
                            legend         : {position : 'right'},
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "85%", height : "85%"}
                        };
                        var chart = new google.visualization.PieChart(document.getElementById('visualizationcolumnProduct'));
                        chart.draw(data, options);
                    }
                    if(responce.pierChartData.brand!==undefined){
                        var data = new google.visualization.DataTable();
                        data.addColumn('string', 'Brand');
                        data.addColumn('number', 'amount');
                        $.each(responce.pierChartData.brand, function(name, values){

                            data.addRows([
                                [name, values*1]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({prefix : '<?php echo $this->currencySymbol;?>', negativeColor : 'red', negativeParens : true});
                        formatter.format(data, 0);
                        formatter.format(data, 1);
                        var options = {
                            legend         : {position : 'right'},
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "85%", height : "85%"}
                        };

                        var chart = new google.visualization.PieChart(document.getElementById('visualizationcolumnBrand'));
                        chart.draw(data, options);
                    }

                    if(responce.pierChartData.tag!==undefined){
                        var data = new google.visualization.DataTable();
                        data.addColumn('string', 'Tag');
                        data.addColumn('number', 'amount');
                        $.each(responce.pierChartData.tag, function(name, values){

                            data.addRows([
                                [name, values*1]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({prefix : '<?php echo $this->currencySymbol;?>', negativeColor : 'red', negativeParens : true});
                        formatter.format(data, 0);
                        formatter.format(data, 1);
                        var options = {
                            legend         : {position : 'right'},
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "85%", height : "85%"}
                        };

                        var chart = new google.visualization.PieChart(document.getElementById('visualizationcolumnTag'));
                        chart.draw(data, options);
                    }
                    if(responce.pierChartData.customer!==undefined){
                        var data = new google.visualization.DataTable();
                        data.addColumn('string', 'Customer');
                        data.addColumn('number', 'amount');
                        $.each(responce.pierChartData.customer, function(name, values){

                            data.addRows([
                                [name, values*1]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({prefix : '<?php echo $this->currencySymbol;?>', negativeColor : 'red', negativeParens : true});
                        formatter.format(data, 0);
                        formatter.format(data, 1);
                        var options = {
                            legend         : {position : 'none'},
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "85%", height : "85%"}
                        };

                        var chart = new google.visualization.PieChart(document.getElementById('visualizationcolumnCustomer'));
                        chart.draw(data, options);
                    }
                    if(responce.pierChartData.type!==undefined){
                        var data = new google.visualization.DataTable();
                        data.addColumn('string', 'Type');
                        data.addColumn('number', 'amount');
                        $.each(responce.pierChartData.type, function(name, values){

                            data.addRows([
                                [name, values*1]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({prefix : '<?php echo $this->currencySymbol;?>', negativeColor : 'red', negativeParens : true});
                        formatter.format(data, 0);
                        formatter.format(data, 1);
                        var options = {
                            legend         : {position : 'none'},
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "85%", height : "85%"}
                        };

                        var chart = new google.visualization.PieChart(document.getElementById('visualizationcolumnType'));
                        chart.draw(data, options);
                    }
                    if (typeof responce.pierChartData.coupon != 'undefined'){
                        var data = new google.visualization.DataTable();
                        data.addColumn('string', 'Coupon');
                        data.addColumn('number', 'amount');
                        $.each(responce.pierChartData.coupon, function(name, values){
                            data.addRows([
                                [name, values*1]
                            ]);
                        });

                        var formatter = new google.visualization.NumberFormat({prefix : '<?php echo $this->currencySymbol;?>', negativeColor : 'red', negativeParens : true});
                        formatter.format(data, 0);
                        formatter.format(data, 1);
                        var options = {
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "85%", height : "85%"}
                        };

                        var chart = new google.visualization.PieChart(document.getElementById('visualizationcolumnCoupon'));
                        chart.draw(data, options);
                    }
                }
                if(responce.pierchartExcistProduct==1) {
                    if (responce.pierChartData.productTable!==undefined) {

                      var dataProduct = new google.visualization.DataTable();
                        dataProduct.addColumn('string', 'Product');
                        dataProduct.addColumn('number', 'amount');
                        $.each(responce.pierChartData.productTable, function (name, values) {
                            dataProduct.addRows([
                                [name, values * 1]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({
                            prefix: '<?php echo $this->currencySymbol;?>',
                            negativeColor: 'red',
                            negativeParens: true
                        });
                        formatter.format(dataProduct, 0);
                        formatter.format(dataProduct, 1);
                        options = {
                            legend:{position:'right'},
                            height:'100%',
                            titleTextStyle: {fontSize:"14"}
                        };
                      var chartProd = new google.visualization.PieChart(document.getElementById('visualizationcolumnProductTable'));
                        chartProd.draw(dataProduct, options);
                        if($.removeCookie('pt') !== false) {
                            $.removeCookie('pt');
                        }

                        function drawCoreProduct(type) {
                            if (type === 'table') {
                                var tableProduct = new google.visualization.Table(document.getElementById('visualizationcolumnProductTable'));
                                tableProduct.draw(dataProduct, {
                                    page: 'enable', pageSize: 15, showRowNumber: true, width: '100%', height: '25px;'
                                }, options);
                            }
                            if (type === 'chart') {
                                var chartProd = new google.visualization.PieChart(document.getElementById('visualizationcolumnProductTable'));
                                chartProd.draw(dataProduct, options);
                            }
                        }
                        $('#viewcorechartproduct').unbind("click");
                        $('#viewcorechartproduct').on('click', function () {
                            if ($.cookie('pt') == 'table') {
                                $.cookie('pt', 'chart');
                            } else {
                                $.cookie('pt', 'table');
                            }
                            drawCoreProduct($.cookie('pt'));
                        });
                        var from = $('#datepickerFrom').val();
                        var to = $("#datepickerTo").val();

                        $('#exportProduct').attr('href', '<?php echo $this->websiteUrl;?>plugin/toasterstats/run/period/type/product/date/'+from+'|'+to);
                    }
                }
                if(responce.pierchartExcistType==1) {
                    if (responce.pierChartData.typeTable!==undefined) {
                        var dataType = new google.visualization.DataTable();
                        dataType.addColumn('string', 'Type');
                        dataType.addColumn('number', 'amount');
                        $.each(responce.pierChartData.typeTable, function(name, values){

                            dataType.addRows([
                                [name, values*1]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({prefix : '<?php echo $this->currencySymbol;?>', negativeColor : 'red', negativeParens : true});
                        formatter.format(dataType, 0);
                        formatter.format(dataType, 1);
                        var options = {
                            legend         : {position : 'none'},
                            titleTextStyle : {fontSize : "14"},
                            chartArea      : {width : "85%", height : "85%"}
                        };

                        var chartType = new google.visualization.PieChart(document.getElementById('visualizationcolumnTypeTable'));
                        chartType.draw(dataType, options);

                        function drawCoreType(type) {
                            if (type === 'tableType') {
                                var tableType = new google.visualization.Table(document.getElementById('visualizationcolumnTypeTable'));
                                tableType.draw(dataType, {
                                    page: 'enable',
                                    pageSize: 15,
                                    showRowNumber: true,
                                    width: '100%',
                                    height: '<?php echo $this->height;?>px'
                                }, options);
                            }
                            if (type === 'chartType') {
                                var chartType = new google.visualization.PieChart(document.getElementById('visualizationcolumnTypeTable'));
                                chartType.draw(dataType, options);
                            }
                        }
                        $('#viewcorecharttype').unbind("click");
                        $('#viewcorecharttype').on('click', function() {
                            if ($.cookie('tp') == 'tableType') {
                                $.cookie('tp', 'chartType');
                            } else {
                                $.cookie('tp', 'tableType');
                            }
                            drawCoreType($.cookie('tp'));
                        });
                        var from = $('#datepickerFrom').val();
                        var to = $("#datepickerTo").val();

                        $('#exportType').attr('href', '<?php echo $this->websiteUrl;?>plugin/toasterstats/run/period/type/type/date/'+from+'|'+to);
                    }
                }
                if(responce.pierchartExcistCustomer==1) {
                    if (responce.pierChartData.customerTable !== undefined) {
                        var dataCustomer = new google.visualization.DataTable();
                        dataCustomer.addColumn('string', 'Customer');
                        dataCustomer.addColumn('number', 'amount');
                        $.each(responce.pierChartData.customerTable, function (name, values) {

                            dataCustomer.addRows([
                                [name, values * 1]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({
                            prefix: '<?php echo $this->currencySymbol;?>',
                            negativeColor: 'red',
                            negativeParens: true
                        });
                        formatter.format(dataCustomer, 0);
                        formatter.format(dataCustomer, 1);
                        var options = {
                            legend: {position: 'none'},
                            titleTextStyle: {fontSize: "14"},
                            chartArea: {width: "85%", height: "85%"}
                        };

                        var chartCustomer = new google.visualization.PieChart(document.getElementById('visualizationcolumnCustomerTable'));
                        chartCustomer.draw(dataCustomer, options);

                        function drawCoreCustomer(type) {
                            if (type === 'tableCustomer') {
                                var tableCustomer = new google.visualization.Table(document.getElementById('visualizationcolumnCustomerTable'));
                                tableCustomer.draw(dataCustomer, {
                                    page: 'enable',
                                    pageSize: 15,
                                    showRowNumber: true,
                                    width: '100%',
                                    height: '<?php echo $this->height;?>px'
                                }, options);
                            }
                            if (type === 'chartCustomer') {
                                var chartCustomer = new google.visualization.PieChart(document.getElementById('visualizationcolumnCustomerTable'));
                                chartCustomer.draw(dataCustomer, options);
                            }
                        }
                        $('#viewcorechartcustomer').unbind("click");
                        $('#viewcorechartcustomer').on('click', function () {
                            if ($.cookie('pc') == 'tableCustomer') {
                                $.cookie('pc', 'chartCustomer');
                            } else {
                                $.cookie('pc', 'tableCustomer');
                            }
                            drawCoreCustomer($.cookie('pc'));
                        });

                        var from = $('#datepickerFrom').val();
                        var to = $("#datepickerTo").val();

                        $('#exportCustomer').attr('href', '<?php echo $this->websiteUrl;?>plugin/toasterstats/run/period/type/customer/date/' + from + '|' + to);
                    }
                }
                if(responce.pierchartExcistBrand==1) {
                    if (responce.pierChartData.brandTable !== undefined) {
                        var dataBrand = new google.visualization.DataTable();
                        dataBrand.addColumn('string', 'Brand');
                        dataBrand.addColumn('number', 'amount');
                        $.each(responce.pierChartData.brandTable, function (name, values) {

                            dataBrand.addRows([
                                [name, values * 1]
                            ]);
                        });
                        var formatter = new google.visualization.NumberFormat({
                            prefix: '<?php echo $this->currencySymbol;?>',
                            negativeColor: 'red',
                            negativeParens: true
                        });
                        formatter.format(dataBrand, 0);
                        formatter.format(dataBrand, 1);
                        var options = {
                            legend: {position: 'right'},
                            titleTextStyle: {fontSize: "14"},
                            chartArea: {width: "85%", height: "85%"}
                        };

                        var chartBrand = new google.visualization.PieChart(document.getElementById('visualizationcolumnBrandTable'));
                        chartBrand.draw(dataBrand, options);

                        function drawCoreBrand(type) {
                            if (type === 'tableBrand') {
                                var tableBrand = new google.visualization.Table(document.getElementById('visualizationcolumnBrandTable'));
                                tableBrand.draw(dataBrand, {
                                    page: 'enable',
                                    pageSize: 15,
                                    showRowNumber: true,
                                    width: '100%',
                                    height: '<?php echo $this->height;?>px'
                                }, options);
                            }
                            if (type === 'chartBrand') {
                                var chartBrand = new google.visualization.PieChart(document.getElementById('visualizationcolumnBrandTable'));
                                chartBrand.draw(dataBrand, options);
                            }
                        }

                        $('#viewcorechartbrand').unbind("click");
                        $('#viewcorechartbrand').on('click', function () {
                            if ($.cookie('bt') == 'tableBrand') {
                                $.cookie('bt', 'chartBrand');
                            } else {
                                $.cookie('bt', 'tableBrand');
                            }
                            drawCoreBrand($.cookie('bt'));
                        });

                        var from = $('#datepickerFrom').val();
                        var to = $("#datepickerTo").val();

                        $('#exportBrand').attr('href', '<?php echo $this->websiteUrl;?>plugin/toasterstats/run/period/type/brand/date/' + from + '|' + to);
                    }
                }

            }
        });
        drawChart();
    }
});
</script>
<div class="DateForSales mt10px p10px">
	<p class="grid_6">
        <label><?php echo $this->translator->translate('Date From');?>:</label>
        <input type="text" id="datepickerFrom">
    </p>
	<p class="grid_6 mt0px">
        <label><?php echo $this->translator->translate('Date To');?>:</label>
        <input type="text" id="datepickerTo">
    </p>
	<label class="checkboxDate grid_12 mb20px pointer">
        <?php echo $this->translator->translate('Check to include taxes');?>
        <input type="checkbox" name="enableTaxesGraf" id="enableTaxesGraf" value="">
    </label>
    <label class="checkboxDate grid_12 mb20px pointer">
        <?php echo $this->translator->translate('Check to include shipping fees');?>
        <input type="checkbox" name="enableShippingForGraf" id="enableShippingForGraf" value="" />
    </label>
	<button class="btn block small blue icon-bars" name="redrawSales" id="redrawSales"><?php echo $this->translator->translate('View Graph');?></button>
</div>