<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/seotoaster-ui.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css'); ?>
<?php echo $this->headLink(); ?>

<div>
    <a href="<?php echo $this->websiteUrl; ?>" title="<?php echo $this->translate('Are you lost?'); ?>">&larr; <?php echo $this->translate('back to'); ?>&nbsp;<?php echo $_SERVER['SERVER_NAME']; ?></a>
</div>

<div class="seotoaster container go-form">
    <div class="header">
        <?php echo $this->translate('Unsubscribe'); ?>
    </div>
    <div class="clear"></div>
    <div class="grid_12">
        <form class="subscribe-reset-form" name="subscribe-reset-form" action="<?php echo $this->websiteUrl;?>plugin/cartstatusemail/run/removeSubscription/" method="POST">
            <label class="mt10px"><?php echo $this->translate('Email Address');?>:</label>
            <input type="text" name="subscribe-email" class="subscribe-email" value="<?php echo $this->subscribeEmail;?>" />
            <input type="hidden" name="unsubscribe-code" class="unsubscribe-code" value="<?php echo $this->unsubscribeCode;?>"/>
            <input type="submit" class="btn unsubscribe-btn mb10px" name="unsubscribe-btn" value="<?php echo $this->translate('Unsubscribe');?>" />
            <input type="hidden" class="secure-token" name="secure-token" value="<?php echo Tools_System_Tools::initSecureToken(Cartstatusemail::CARTSTATUS_SECURE_TOKEN);?>">
        </form>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $('.subscribe-reset-form').on('submit', function(e){
            e.preventDefault();
            var email = $(this).find('.subscribe-email').val(),
                code = $(this).find('.unsubscribe-code').val(),
                token = $(this).find('.secure-token').val();
            $.post('<?php echo $this->websiteUrl;?>plugin/cartstatusemail/run/removeSubscription/', {'email':email, 'code':code, 'secureToken':token }, function(response){
                if (response.error == 1) {
                    showMessage('<?php echo $this->translate('Wrong email address');?>');
                } else {
                    showMessage('<?php echo $this->translate('You’ve been unsubscribed from our automated email system.');?>', false, 5000);
                    window.location.href = '<?php echo $this->websiteUrl;?>';
                }

            }, 'json');
        });

    });
</script>