<div id="cart-summary">
    <h3 class="checkout-widget-title">
	    <?php echo $this->translate('Summary'); ?>
	</h3>
	<div class="cart-summary-row cart-subtotal">
		<span><?php echo $this->translate('Subtotal'); ?>:</span>
		<span id="subtotal-val">
        <?php if ($this->taxIncPrice) : ?>
            <?php echo $this->currency($this->summary['subTotal']+$this->summary['subTotalTax']); ?>
        <?php else : ?>
            <?php echo $this->currency($this->summary['subTotal']); ?>
        <?php endif; ?>  
        </span>
	</div>
    <?php if (isset($this->summary['discount']) && !empty($this->summary['discount'])) : ?>
        <div class="cart-summary-row cart-discount">
            <span><?php echo $this->translate('Discount'); ?></span>
            <?php if ($this->taxIncPrice) : ?>
                <span id="discount-val"><?php echo $this->currency($this->summary['discount']+$this->summary['discountTax']); ?></span>
            <?php else:?>
                <span id="discount-val"><?php echo $this->currency($this->summary['discount']); ?></span>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <div class="cart-summary-row cart-shipping">
        <span><?php echo $this->translate('Shipping'); ?>:</span>
        <?php if ($this->taxIncPrice) : ?>
            <span id="shipping-val"><?php echo $this->currency($this->summary['shipping']+$this->summary['shippingTax']); ?></span>
        <?php else:?>
            <span id="shipping-val"><?php echo $this->currency($this->summary['shipping']); ?></span>
        <?php endif;?>
    </div>
	<div class="cart-summary-row cart-total-tax">
		<?php if(Tools_Misc::getTaxName() != ''):?>
            <?php $taxName = Tools_Misc::getTaxName();?>
        <?php else:?>
            <?php $taxName = 'Tax';?>
        <?php endif;?>
        <?php if ($this->taxIncPrice) : ?>
		<span><?php echo $this->translate('Inc. '.$taxName); ?>:</span>
		<?php else : ?>
		<span><?php echo $this->translate('Total '.$taxName); ?>:</span>
		<?php endif; ?>
		<span id="totaltax-val"><?php echo $this->currency($this->summary['totalTax']);?></span>
	</div>

	<div class="cart-summary-row cart-total">
		<span><?php echo $this->translate('Total'); ?>:</span>
		<span id="total-val"><?php echo $this->currency($this->summary['total']); ?></span>
	</div>
	
	
<!-- Paypal Express -->	
	
<div id="paypal-button"></div>

<script src="https://www.paypalobjects.com/api/checkout.js"></script>


<div id="paypal-button-container"></div>

    <script>
    
    
   
     
    
    
    
    
       <?php
       
			
       
         $price=$this->summary['total']; //Total Price for Payment
        
			echo"var price='$price';";
			
			
			
			
					
	
			
		?>
    
        paypal.Button.render({
        	
   


            env: 'sandbox', // sandbox | production

            // PayPal Client IDs - replace with your own
            // Create a PayPal app: https://developer.paypal.com/developer/applications/create
            client: {
                sandbox:    'AVWwnmz32wlzFqogw9E93H82FlVYWvMUXohxKnITuIlMJDwQCGge8_nqRI-iMxNmPktOG1DRgmHTfpUK',
                production: '<insert production client id>'
            },

            // Show the buyer a 'Pay Now' button in the checkout flow
            commit: true,

            // payment() is called when the button is clicked
            payment: function(data, actions) {

                // Make a call to the REST api to create the payment
                return actions.payment.create({
                    payment: {
                        transactions: [
                            {
                                amount: { total: price, currency: 'EUR' }
                            }
                        ]
                    }
                });
            },

            // onAuthorize() is called when the buyer approves the payment
            onAuthorize: function(data, actions) {
            
            
            
          
            return actions.payment.get().then(function(paymentDetails) {
            
          var info=paymentDetails;
            

                // Make a call to the REST api to execute the payment
                return actions.payment.execute().then(function() {
              
              var name=info.payer.payer_info.first_name;
					
					console.log(name);
                    window.alert(info);
                });
           });
           
            }

        }, '#paypal-button-container');

    </script>
	
	
</div>