<?php
    if($this->currentUserRole === Tools_Security_Acl::ROLE_SUPERADMIN) {
        if( !$this->noScript ) {
            $this->inlineScript()
                 ->appendFile($this->websiteUrl."plugins/widcard/system/js/widcard.min.js");
        }
    }
?>
<?php if($this->href) {echo rawurlencode($this->fieldValue); return false;}?>
<?php if($this->currentUserRole === Tools_Security_Acl::ROLE_SUPERADMIN) :?>
    <?php if($this->notag || $this->src) {
        echo $this->fieldValue;
        return false;
    }?>
    <?php if($this->locationBlock && $this->image) :
        echo $this->fieldValue;
    ?>
        <a class="tpopup" data-pheight="560" data-pwidth="480" data-url="<?php echo $this->websiteUrl;?>plugin/widcard/run/getWebsiteIdCard" href="javascript:;"><img class="wicIcon" src="<?php echo $this->websiteUrl;?>plugins/widcard/system/images/edit.png" width="20px" alt="" /></a>
    <?php endif;?>

    <?php if($this->actionUrl && !$this->locationBlock) :?>
    <span data-secure-token="<?php echo $this->secureToken;?>" title="<?php echo $this->fieldTitle?>" id="<?php echo $this->fieldName?>" class="wicInlineElement" data-default="<?php echo ($this->default) ? true : false ;?>" data-url="<?php echo $this->actionUrl;?>"><?php echo $this->fieldValue;?></span><img style="display: none; width:auto; height: auto;" src="<?php echo $this->websiteUrl;?>plugins/widcard/system/images/load.gif" width="35px" height="10px" alt="" />
    <a class="tpopup" data-pheight="560" data-pwidth="480" data-url="<?php echo $this->websiteUrl;?>plugin/widcard/run/getWebsiteIdCard" href="javascript:;"><img class="wicIcon" src="<?php echo $this->websiteUrl;?>plugins/widcard/system/images/edit.png" width="20px" alt="" /></a>
    <?php endif;?>

    <?php if($this->locationBlock && !$this->image) :?>
    <span data-secure-token="<?php echo $this->secureToken;?>" title="<?php echo $this->fieldTitle?>"><?php echo $this->fieldValue;?></span>
    <a class="tpopup" title="<?php echo $this->fieldTitle?>" data-pheight="560" data-pwidth="480" data-url="<?php echo $this->websiteUrl;?>plugin/widcard/run/getWebsiteIdCard" href="javascript:;"><img class="wicIcon" src="<?php echo $this->websiteUrl;?>plugins/widcard/system/images/edit.png" width="20px" alt="<?php echo $this->fieldTitle?>" title="<?php echo $this->fieldTitle?>" /></a>
    <?php endif;?>
<?php else:?>
        <?php echo $this->fieldValue;?>
<?php endif;?>