<?php if(isset($this->content)):?>
    <?php echo ($this->content);?>
<?php endif; ?>
<?php  if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_CONTENT) && !$this->readonly):?>
    <a  href="javascript:;" class="tpopup" data-url="<?php echo $this->websiteUrl?>plugin/webbuilder/run/featuredonly/?container=<?php echo $this->container?>&pageId=<?php echo $this->pageId?>" title="<?php echo $this->translate('Edit areas');?>"  data-pwidth="300" data-pheight="320">
        <img alt="Featured Page List" src="<?php echo $this->websiteUrl."plugins/webbuilder/web/images/featuredpageslist.png";?>"/>
    </a>
<?php endif;?>