<?php if($this->content): ?>
    <?php echo $this->content ?>
<?php endif; ?>
<?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_CONTENT) && !$this->readonly):?>
    <a href="javascript:;" data-url="<?php echo $this->websiteUrl;?>plugin/webbuilder/run/textonly/container/<?php echo $this->container;?>/pageId/<?php echo $this->pageId;?>" title="<?php echo $this->translate('Edit text'); ?>" class="tpopup" data-pwidth="720" data-pheight="560">
        <img alt="<?php echo $this->translate('Text only'); ?>" src="<?php echo $this->websiteUrl; ?>plugins/webbuilder/web/images/textonly.png"/>
    </a>
<?php endif;?>