<?php if ($this->pageCount && $this->pageCount > 1): ?>
    <li class="news-list-pagination paginator">
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url?>?listname=<?php echo $this->listName ?>&pnum=<?php echo $this->previous, $this->tags; ?>"><?php echo $this->translate('Previous'); ?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $this->translate('Previous'); ?></span>
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url?>?listname=<?php echo $this->listName ?>&pnum=<?php echo $page, $this->tags; ?>"><?php echo $page; ?></a>
            <?php else: ?>
                <span class='current'><?php echo $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url?>?listname=<?php echo $this->listName ?>&pnum=<?php echo $this->next, $this->tags; ?>"><?php echo $this->translate('Next'); ?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $this->translate('Next'); ?></span>
        <?php endif; ?>
    </li>
<?php endif; ?>